### PR TITLE
Add platform support to docs

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by peter-b** [comment]
@montegoulding It looks like you need to tweak your Travis configuration so that Travis only tries to deploy from the `master` branch.

Otherwise, this looks good to me 👍

**Comment by montegoulding** [comment]
Hmm... it used to only deploy from tags. Is that a recent change.

**Comment by peter-b** [comment]
@montegoulding Not sure but you've definitely got a deploy failure going on there!

**Comment by montegoulding** [comment]
Yes I can see... checking the docs now

**Pull request merged**
